version: "3.7"
services:
  dhcpd:
    build: 
      context: dhcpd/
    network_mode: host
    ports:
      - target: 67
        published: 67
        protocol: udp
        mode: host
    volumes:
      - /srv/data/deploy/dhcpd:/etc/dhcp
    restart: always

  named:
    build:
      context: named/
    # HACK cmm - workaround for ip masquerade issue
    network_mode: host
    ports:
      - target: 53
        published: 53
        protocol: tcp
        mode: host
      - target: 53
        published: 53
        protocol: udp
        mode: host
    volumes:
      - /srv/data/deploy/named/var/named:/var/named
      - /srv/data/deploy/named/etc/named.conf:/etc/named.conf
    restart: always

  registry:
    image: "registry:2"
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
        mode: host
    volumes:
      - /srv/data/deploy/registry:/var/lib/registry
    restart: always

  tftpd:
    build:
      context: tftpd/
    network_mode: host
    ports:
      - target: 69
        published: 69
        protocol: udp
        mode: host
    volumes:
      - /srv/data/deploy/tftpd:/srv/tftp
      - /srv/img:/srv/tftp/img
    restart: always

  vault:
    build:
      args:
        vault_release: "1.5.3"
      context: vault/
    cap_add:
      - IPC_LOCK
    ports:
      - target: 8200
        published: 8200
        protocol: tcp
        mode: host
    volumes:
      - /srv/data/deploy/vault:/vault
    restart: always

  www:
    build:
      context: www/
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - /srv/data/deploy/www:/var/www/html
      - /srv/img:/var/www/html/img
      - /srv/data/deploy/tftpd/cfg:/var/www/html/cfg
      - /usr/lib/syslinux:/var/www/html/syslinux:ro
      #- /srv/data/deploy/apt-mirror/mirror/archive.ubuntu.com/ubuntu:/var/www/html/ubuntu
    restart: always


